CREATE TABLE Geek(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
nom varchar(25) NOT NULL,
prenom varchar(25) NOT NULL, 
mail varchar(40) NOT NULL,
sexe char(1) NOT NULL,
gravatar varchar(256),
PRIMARY KEY(Id)
)

CREATE TABLE Interet(
Id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
nom varchar(25) NOT NULL,
description varchar(100) NOT NULL, 
PRIMARY KEY(Id)
)

CREATE TABLE Geek_Interet(
IdGeek int,
IdInteret int,
PRIMARY KEY(IdGeek, IdInteret),
FOREIGN KEY (IdGeek) References Geek(ID),
FOREIGN KEY (IdInteret) References Interet(ID)
)

CREATE TABLE consultation (
id integer NOT NULL,
date timestamp NOT NULL,
ip VARCHAR(255) NOT NULL,
geek integer NOT NULL,
primary KEY (id),
FOREIGN KEY (geek) REFERENCES Geek(id)
);
INSERT INTO GEEK (prenom, nom,mail,sexe,gravatar) values ('Maroua','OTHMAN','MAROUA241@gmail.com', 'f', '/img/maroua.png')
INSERT INTO GEEK (prenom, nom,mail,sexe, gravatar) values ('Alex','Dupond','alex@gmail.com', 'M', '/img/alex.jpg')
INSERT INTO GEEK (prenom, nom,mail,sexe, gravatar) values ('Marie','Dupond', ' marie@gmail.com', 'm', '/img/marie.jpg')

INSERT INTO INTERET (NOM,DESCRIPTION) VALUES ('PHP','Langage  web')
INSERT INTO INTERET (NOM,DESCRIPTION) VALUES ('JAVA', 'Meilleur Langage')
INSERT INTO INTERET (NOM,DESCRIPTION) VALUES ('CSharp',' Langage')

INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (1 ,3 )

INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (2 ,1 )
INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (2 ,2 )

INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (3 ,1 )
INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (3 ,2 )
INSERT INTO "PUBLIC"."GEEK_INTERET" ( "IDGEEK", "IDINTERET" ) VALUES (3 ,3 )
